//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 转义字符：
        ///文字替换：
        ///括号内容：
        ///删除空格：
        ///换行符相关：
        ///文字顺序调换：
        ///逐行添加内容：
        ///段首添加序号：
        ///文本格式转换：
        ///自定义转换列表：
        ///隔行删除：
        ///隔行插入：
        ///特殊插入：
        ///正则表达式：
        ///文件重命名：
        ///剪贴板辅助工具： 的本地化字符串。
        /// </summary>
        internal static string HelpTextList {
            get {
                return ResourceManager.GetString("HelpTextList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;property&gt;
        ///  &lt;version&gt;第四版&lt;/version&gt;
        ///  &lt;number&gt;2.5.0&lt;/number&gt;
        ///  &lt;autoClear value=&quot;False&quot; /&gt;
        ///  &lt;memoryCount value=&quot;10&quot; /&gt;
        ///  &lt;clearAfterCopy value=&quot;False&quot; /&gt;
        ///  &lt;textBoxColor value=&quot;白色&quot; /&gt;
        ///  &lt;autoSaveTemp value=&quot;True&quot; /&gt;
        ///  &lt;showSpeed value=&quot;False&quot; /&gt;
        ///  &lt;alwaysShowBox2 value=&quot;False&quot; /&gt;
        ///&lt;/property&gt; 的本地化字符串。
        /// </summary>
        internal static string InitialConfig {
            get {
                return ResourceManager.GetString("InitialConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2.5.0
        ///v2.4.3
        ///v2.4.2
        ///v2.4.1
        ///v2.4.0
        ///v2.3.0
        ///v2.2.5
        ///v2.2.0
        ///v2.1.0
        ///v2.0.5
        ///v2.0.1
        ///v2.0.0
        ///v1.4.0
        ///v1.3.0
        ///v1.2.6
        ///v1.2.5
        ///v1.2.1
        ///v1.2.0
        ///v1.1.6
        ///v1.1.5
        ///v1.1.2
        ///v1.1.1
        ///v1.1.0
        ///v1.0.0 的本地化字符串。
        /// </summary>
        internal static string VersionTextList {
            get {
                return ResourceManager.GetString("VersionTextList", resourceCulture);
            }
        }
    }
}
